# Generated by Django 3.2.5 on 2021-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210725_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
